Ctrl+0     script-message mount 0
Ctrl+1     script-message mount 1
Ctrl+2     script-message mount 2
Ctrl+3     script-message mount 3
Ctrl+4     script-message mount 4
Ctrl+5     script-message mount 5
Ctrl+6     script-message mount 6
Ctrl+7     script-message mount 7
Ctrl+8     script-message mount 8
Ctrl+9     script-message mount 9
