packages:
  - 'mpv-*'
allowBuilds:
  canvas: true
  core-js: true
  esbuild: true
  lefthook: true
minimumReleaseAgeExclude:
  - webdav-parser@0.1.0
  - jdl@0.1.5
  - '@easy-install/easy-archive@0.2.7'
